import { DM_Sans, Poltawski_Nowy } from "next/font/google";

import "./globals.css";

const dmFont = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const poltawski = Poltawski_Nowy({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmFont.className} ${poltawski.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
